export default function() {
    return [{
            title: 'Magician: Apprentice',
            description: "At Crydee, a frontier outpost in the tranquil Kingdom of the Isles, an orphan boy, Pug, is apprenticed to a master magician - and the destinies of two worlds are changed forever. Suddenly the peace of the Kingdom is destroyed as mysterious alien invaders swarm through the land. Pug is swept up into conflict but for him and his warrior friend, Tomas, an Odyssey into the unknown has only just begun. Pug's destiny is to lead him through a rift in the fabric of space and time to the mastery of the unimaginable powers of a strange new magic ...",
            previewImg: 'https://images-na.ssl-images-amazon.com/images/I/5142ES9VS1L._SX287_BO1,204,203,200_.jpg'
        },
        {
            title: 'Magician: Master',
            description: "Magician Master is the second half of the book Magician."
        },
        {
            title: 'Silverthron',
            description: "Silverthorn is the astonishing sequel to Magician - and an even more stirring tale of the imagination. Once again the magical worlds of Midkemia and Kelewan come alive, peopled with princes, kings, squires - and warriors. In Silverthorn a new evil power that raises the dead and makes corpses do battle with the living threatens the new king of Midkemia. And a life-or-death quest is undertaken for an antidote to a poison that fells a beautiful princess on her wedding day. Silverthorn is a stirring tale of magic, chivalry and romance. It is a worthy successor to Magician - and an exciting prelude to the final volume in the Riftwar Saga, Darkness at Sethanon"
        },
        {
            title: 'A Darkness At Sethanon',
            description: "A Darkness at Sethanon is the stunning climax to Raymond E. Feist's brilliant epic fantasy trilogy, the Riftwar Saga. Here be dragons and sorcery, swordplay, quests, pursuits, intrigues, stratagems, journeys to the darkest realms of the dead and titanic battles between the forces of good and darkest evil. Here is the final dramatic confrontation between Arutha and Murmandamus - and the perilous quest of Pug the magician and Tomas the warrior for Macros the Black. A Darkness at Sethanon is heroic fantasy of the highest excitement and on the grandest scale, a magnificent conclusion to one of the great fantasy sagas of our time."
        },
        {
            title: 'Daughter of the Empire',
            description: "Now, from the imagination of two of fantasy fiction's hottest young talents, comes an astonishing epic that takes readers into the heart of the exotic Tsurani empire, where formal courts mask deadly intrigues. Murder and magic encircle the mysterious world of Kelewan, where a valiant girl leads her followers through terror and peril - and discovers her own womanhood. She is Mara, Ruling Lady of the Acoma, who in her heroic struggles for survival must contend with powerful rival houses, strike deals with sinister rebel warriors, and forge a treaty with the enigmatic Cho-ja - a race of alien insectoids. But in order to restore the house to pre-eminence Mara must trade her heart for power as she marries the son of an enemy - all the while plotting his death. Mara's bold and desperate gamble enables her to get past assassinations and betrayal until she must confront her most dangerous foe. In his own stronghold..."
        },
        {
            title: 'Prince of the Blood',
            description: "Set twenty years after the events so brilliantly told in his Riftwar Saga, Prince of the Blood follows the intrigues and adventures that erupt when a group of powerful nobles attempt to overthrow the Empress of Kesh, ending her bloodline and bitterly dividing the court. In the centre of the conflict are two princes of Krondor, Boric and Erlund. When Boric is captured and learns of the plot to kill them both, he escapes and makes a desperate journey back to the court to warn of the traitors' plans - which, if they were to succeed, would start a war that would tear the Empire apart."
        },
        {
            title: 'Servant of the Empire',
            description: "The brilliant, eagerly-awaited sequel to Daughter of the Empire. Mara of Acoma, Ruling Lady of her house, has now established herself as a force within the Empire. As an expert player of the Game of the Council., she is a master of its bloody political maneuvering. Mara has made gains for her followers, including new lands, but the war effort on the world of Midkemia is draining off manpower, and slaves are difficult to find.. So against advice, Mara buys a group of Midkemian prisoners-of-war, only to discover that one of them is a noble: Kevin, third son of the Baron of Zun. Questioning soon reveals that he may be of great use to her in the next rounds of the Game of the Council."
        },
        {
            title: 'Mistress of the Empire',
            description: "This stunning finale to the Empire series concludes the compelling story of one woman's battle to conquer and transform her world. Daughter of the Empire began the epic saga of Mara of the Acoma, illustrating her meteoric rise to power in the Machiavellian intrigues of the Tsurani court. Servant of the Empire continued that tale as Mara, Ruling Lady of her house, established herself as a skilful player in the Game of the Council. Now Mara faces not only the brotherhood of assassins, and the cunning spies of the rival ruling houses, but the awesome Assembly of Magicians, who see her as the ultimate threat to their ancient power."
        },
        {
            title: 'The Kings Buccaneer',
            description: "THE PEACE CRUMBLES ... Set ten years after the events recounted in Prince of the Blood, The King's Buccaneer is a new and exciting epic adventure from one of the world's most popular fantasy writers. Long recovered from the ravages of the Riftwar, the people in the Kingdom of the Isles enjoy peace and prosperity. Nicholas, third son of Prince Arutha of Krondor, is a bright and gifted youngster, but sheltered by the restrictive life of his father's court. To learn more of the world outside the palace walls, Nicholas and his squire, Harry, set sail for pastoral Crydee. Shortly after their arrival, Crydee. is brutally attacked by unknown forces. The castle is reduced to ruins, the townspeople slaughtered and two young noblewomen - friends of Nicholas - abducted. Soon the young Prince and his companions discover that the surprise attack was no isolated incident."
        },
        {
            title: 'Shadow of a Dark Queen',
            description: "Something dark is moving in distant nations, and ancient powers ready themselves for a final confrontation. A Dark Queen has raised a standard in remote lands and is gathering armies of unmatched might. nto this battleground of good and evil come a band of 'desperate men' who will embark on a quest that is at best dangerous and at worst suicidal. Among them is Nakor the Isalani, a gambler who knows more magic than most magicians, yet who claims magic doesn't exist. He alone knows the true nature of the Dark Queen whose shadow threatens to engulf their world. And travelling with the group is the mysterious Miranda upon whom all must wager their lives. She appears to be an ally but knows much more than she is willing to tell. Does she have a hidden agenda of her own And will she prove ally or even more deadly foe when the final confrontation is at hand."
        },
        {
            title: 'Rise of a Merchant Prince',
            description: "Roo Avery, recently returned from a harrowing brush with the armies of the Emerald Queen, is now free to choose his own destiny and his ultimate ambition is to become one of the richest and most powerful merchants in Midkemia. But nothing can prepare him for the dangers of the new life he has chosen where the demand for repayment of a debt can be as deadly as a knife in the shadows. Even those closest to him are suspect and as Roo struggles to build his financial empire, betrayel is forever close at hand. His instinctive cunning will serve him well, but he will soon realise that the road to success is far from smooth. And while Roo works towards achieving his goal, the memory of the distant forces of darkness are never far away. For the war with the Emerald Queen is far from over and the inevitable confrontation will pose the biggest threat yet to his new found wealth and power."
        },
        {
            title: 'Rage of a Demon King',
            description: "MACROS THE BLACK IS BACK ... Midkemia once again lies under the terrible shadow of the Emerald Queen. Her dark forces are ready to launch a devastating invasion against the Kingdom of the Isles. Come the battle's dawn the magician Pug, along with his life-long warrior friend Tomas, discover that something far worse than the Queen's mere sorcery is afoot. For elemental, malevolent forces are being unleashed...forces that threaten to tear Midkemia apart unless Pug and his band of supporters can track down the long-missing sorcerer Macros the Black and confront his formidable powers."
        },
        {
            title: 'Shards of a Broken Crown',
            description: "THE DEMON IS NO MORE ... The enemy has been routed, yet peace still eludes the Kingdom. Midkemia lies in smouldering ruins following the Demon King's siege. Many lives have been lost, including that of the brave James, Duke of Krondor. As the people turn their hands to rebuilding their once great nation, a new threat arises from the ashes of war: the fearsome Fadawah, Former Commanding General of the Army of the Emerald Queen. He has grasped the fallen reins of command and seeks to forge a personal empire out of the wreckage of the Western Realm. And so it falls to two young men - Jimmy and Dash - grandsons of the late Duke, to gather together the shards of the broken crown and resurrect the Kingdom to its former glory. Shards of a Broken Crown - the unforgettable finale to the world wide best-selling Serpentwar Saga."
        },
        {
            title: 'Krondor the Betrayal',
            description: "A spellbinding new Riftwar adventure featuring old favourites Jimmy, Locklear and Pug... It is nine years on from the aftermath of Sethanon and news is feeding through to the people of the Kingdom of the Isles that deadly forces are stirring on the horizon. the bringer of the latest grim tidings is Gorath, a moredhel (dark elf). The bloodletting has started. Nighthawks are murdering again. Politics is a dangerous, cut-throat game once more. At the root of all this unrest lie the mysterious machinations of a group of magicians known as the Six. Meanwhile, renegade Tsurani gem smugglers, a rival criminal gang to the Mockers led by someone known only as the Crawler, and traitors to the crown, are all conspiring to bring the Kingdom of the Isles to its knees."
        },
        {
            title: 'Krondor the Assassins',
            description: "The Assassin's Guild returns to Krondor, seemingly killing without pattern or purpose. Squire James and newly commissioned Lieutenant William conDoin are plummeted into a dark world of Murder and politics as war threatens to engulf the Kingdom, for among those murdered is a noble from a neighbouring state. Time is short and the city is gripped in terror as the two young men race to find the man responsible for this act of war, a mysterious figure known as the Crawler."
        },
        {
            title: 'Krondor Tear of the Gods',
            description: "A raid upon the high seas signals an attack of unprecedented magnitude by the forces of darkness. For the holiest of holies, the Tear of the Gods has been lost to the Temple of Ishap. After a raid planned by Bear, one of the most brutal pirates to sail the Bitter Sea, goes dramatically wrong, the colossal gem sinks below the waves. Only one man survives with knowledge of its exact location. But he's gone underground in Krondor. He is Knute, treacherous pilot of the pirate ship. Bear wants him alive - until he extracts the information he needs, by whatever means necessary. So begins the story of the Tear of the Gods, the most powerful artifact known to the Temples of Midkemia. since it allows the temples to speak with their gods. Without it, they will be lost for a decade, until another gem is formed in the distant mountains Squire James, William, and Jazhara, new court magician, must seek out the location of this gem, with Brother Solon, a warrior priest of Ishap, and Kendaric, the sole member of the Wreckers' Guild with the power to raise the ship. They are opposed by the minions of Sidi, servant of the Dark God, who seeks to possess the Tear for his own ends, or to destroy it, denying it to the forces of light. This third tale in the Riftwar Legacy is a breathless race for priceless treasure. It's a race against time, against the myriad sinister and competing evil forces desperate for the all-powerful prize, and ultimately against the fundamentals of nature, which in Midkemia can be as formidable as the Gods themselves..."
        },
        {
            title: 'Honoured Enemy',
            description: "Freedom at any price ? Hartraft's Marauders, a crack band of Kingdom raiders, are a special unit designed to infiltrate and fight behind enemy lines. They are currently heading for a frontier garrison, after a disastrous encounter with the Tsurani. Meanwhile, a Tsurani patrol is sent to support an assault on the same garrison. Both sides arrive at the same time and discover the garrison has been overrun by a migrating horde of moredhel (dark elves) and they are forced by circumstances to band together and fight as one to survive. The only problem is, who do they hate the most - their mutual enemy, or each other? As they make their way across the unknown Northlands to freedom, they have to struggle not only with the elements and their enemies, but also their conscience. For what is more important - one's life? or one's honour?"
        },
        {
            title: 'Murder in LaMut',
            description: "The heavy action was supposedly at Crydee these days which meant that the one place they could be sure the three of them were not going was Crydee. Come spring, the privateer Melanie was due in Ylith, and its captain could be counted on for a swift conveyance away for sure, and likely not to murder them in their sleep. That would be bad for business. But away where? That wasnt Durines worry. Kethol would surely be able to find the three of them somebody who needed men who knew which part of the sword you used to cut with and which part you used to butter your bread, and Pirojil would be able to negotiate a price at least half again what the employer was ready to pay. All Durine would have to do was kill people. That was fine with him. Durine, Kethol and Pirojil are three mercenaries who have spent twenty years fighting other peoples battles: against the Tsurani and the Bugs and the goblins, and now it seems theyve run out of Tsurani, Bugs and goblins to kill. The prospect of a few months of garrison duty offers a welcome respite; but then they are given an assignment that seems, on the surface, like cushy work to protect a lady and her husband and deliver them safely to the city of LaMut"
        },
        {
            title: 'Talon of the Silver Hawk',
            description: "Among the Orosini tribe, every boy must undergo the traditional manhood ritual in order to understand his place in the universe and discover his manhood name. Kielianapuna must survive on the remote mountain peak of Shatana Higo until the gods grant him his vision. But Kieli has already waited for four days and nights, and now he is cold, lonely, despairing, and very, very tired ... When he is woken by the terrifying sensation of sharp claws piercing his skin and finds a rare silver hawk upon his arm, it is such a disorientating moment that he is not sure whether it has even happened, or whether it was a vision. Returning to his home, nameless and still a child, Kieli stumbles upon devastation. His village is being burned, his people slaughtered. Although it means certain death, Kieli throws himself into the battle ... Against all the odds, he survives, alone of all the Orosini, who have been cut down where they stand: every last man, woman and child. A distant voice echoes in his mind: Rise up and be a talon for your people ... The visitation of the bird on Shatana Higo was indeed his naming vision. He is a boy called Kielianapuna no more. Now he is Talon of the Silver Hawk, a man who must avenge the murder of his people, whatever that may take..."
        },
        {
            title: 'Jimmy the Hand',
            description: "Jimmy the Hand, boy thief of Krondor, lived in the shadows of the city. The sewers were his byways and a flea-ridden, rat infested cellar his home. Although gifted beyond his peers, he was still but a nimble street urchin, a pickpocket with potential. Until the day he met Prince Arutha. Aiding the Prince in his rescue of Princess Anita from imprisonment by Duke Guy du Bas-Tyra, Jimmy ran afoul of Black Guy's secret police. But his situation gets worse when he blatantly disregards the Upright Man's instruction to lie-low in order to rescue his fellow Mockers from the cruel reprisal of the Dukes henchmen. Given the choice of disapearing on his own, or with the Upright Man's help - in a weighted barrel at the bottom of Krondor's harbour - Jimmy flees the only home he's ever known, and ventures south to the relatively safe haven of Lands End. Suspecting the rural villagers have never encountered a lad with his talent and nose for finding wealth - other peoples wealth, he's fairly optimistic about his broadening his horizons. But Jimmy is completely unprepared for what greets him. For Lands End is home to others who tred the crooked path, and more, to a darker secret; a dangerous presence unknown to even the local thieves and smugglers. Jimmy's youthful bravado and courage plunge him deep into the maw of chaos and death."
        },
        {
            title: 'King of Foxes',
            description: "Talon, last of the Orosini tribe has been transformed by the Conclave of Shadows from a trusting young boy to the dashing young nobleman Talwin Hawkins, now Roldem's premier swordsman. The title, won at the Masters Court, before the King, brought him a step closer to his desire - to avenge the massacre of his family. Two participants in the slaughter are dead by his hand; Lieutenant Campaneal fell under his blade during the Master's Tournament and the other, Raven, died whilst attempting to butcher an Orodon village, just as he destroyed Tal's people. But Tal's desire for vengeance will not be satisfied until the reason for the massacres has been uncovered and their architect revealed and punished. The Conclave demands its membership price from Tal: he must gather information on Laso Varen, a magician of terrible power and subtle craft, dangerous beyond contemplation. And to do this means service with the sorcerer's master, Duke Kaspar of Olasko - and swearing loyalty to the very man who ordered the destruction of everything Tal loved. Tal must now face the dilema of serving two masters, two deadly enemies: Kaspar Olasko and the Conclave of Shadows."
        },
        {
            title: 'Exiles Return',
            description: "Once absolute ruler of his nation Kaspar, former Duke of Olasko, has been cast into exile. Abandoned in the wilds of a continent on the other side of the world and left with nothing but his wits and determination, he must fight merely to survive. Armed with guile, cunning and an iron will, he starts his odyssey with a single goal: to return to his home and revenge himself upon the man who cast him down, Talwin Hawkins. But fate has other plans for Kaspar, and as he struggles against adversity, he encounters dangers greater than any he had imagined. More is at stake than he realised and Kaspar is but a single player in a far greater game than he imagined, for pitted against the Conclave of Shadows are the agents of the Dark Empire, a looming menace that threatens not only Kaspar's homeland, but the entire world of Midkemia."
        },
        {
            title: 'Flight of the NightHawks',
            description: "A new evil threatens Midkemia, its web stretching from the deepest criminal underworld all the way up to the highest seats of power in ancient Kesh. And the Conclave of Shadows, charged unexpectedly with the training of two apprentices, must also best powerful agents of the darkest magic ... for the fate of two worlds lies in the balance. Raymond E. Feist returns to his signature world of Midkemia in this first book in a new trilogy that ushers in the third, and most dramatic, Riftwar yet: the Darkwar. In the middle of the night on Sorcerer's Isle, the powerful sorcerer Pug is awakened from a nightmare that portends destruction for all of Midkemia. Disturbed by the dream, Pug calls for a convening of the Conclave of Shadows. Though Pug does not yet know it, his son Magnus has discovered the cause of Pug's prophetic dream: a beacon has been unleashed, directing a vast army of alien invaders to Midkemia, an army so formidable that even the might of the Tsurani Empire might fall before its fury. Meanwhile, in far Stardock town, two boys are coming of age. But on the dusty path that leads them from home they are thrust by fate into a life undreamed of, becoming enmeshed in intrigue, murder, and treason. Though untrained and unready, they are called upon by the mysterious Conclave to travel deep into the heart of the Empire of Great Kesh, to confront a plot so dark and twisted it will implicate even the highest-ranking nobles of the Empire, even members of the royal family itself. And behind this plot they discover the ancient Brotherhood of Death, the clan of assassins known as the Nighthawks. And Pug will find himself once again facing his old nemesis, the evil wizard formerly known as Sidi, now Leso Varen, in a confrontation with everything at stake: his honour, his life, and the future of Midkemia."
        },
        {
            title: 'Into a Dark Realm',
            description: "Chaos threatens to overwhelm two worlds as the most dangerous force ever encountered threatens to invade Midkemia, while the most treacherous magician in history - the madman Leso Varen - begins to wreak havoc on the world of Kelewan. Pug and the Conclave of Shadows are determined to find Varen, only to discover that he has usurped the body of one of the most powerful men in the Empire of Tsuranuani - a Black Robe and member of the Assembly of Magicians. Pug has the almost impossible task of uncovering the true identity of the fiendish magician in an entire city full of Black Robes. Murder, mayhem, horror, and the darkest evil await Pug's son, Magnus, and his companions as they attempt to discover the ultimate source of the terrible threat that hovers over Midkemia and Kelewan. Leading a desperate expedition into the realm of the Dasati, the vast and malevolent empire which is threatening his homeworld, Magnus hopes to find the key to defeating this enemy who is capable of overwhelming the combined might of two worlds. But even if he does, the companions will have a desperate struggle to return home with their vital information. Three worlds will teeter on the brink of destruction as the third Riftwar: the Darkwar, is unleashed."
        },
        {
            title: 'Wrath of a Mad God',
            description: "The Darkwar has fallen upon the worlds of Kelewan and Midkemia; a time of heroes, trials and destruction. Following their dangerous mission to the realm of the alien Dasati, Magnus and the other members of the Conclave must now find a way to use what they discovered to help save their own people from the Wrath of a Mad God."
        },
        {
            title: 'Rides a Dread Legion',
            description: "The first book in a brand new 2 book series by the master of epic fantasy, Raymond E. Feist. Ten years after the cataclysmic events of Wrath of a Mad God took place, Midkemia now faces a new danger thought buried in myth and antiquity. A lost race of elves, the taredhel or ‘people of the stars’, have found a way across the universe to reach Midkemia. On their current home world, these elves are hard pressed by a ravaging demon horde, and what was once a huge empire has been reduced to a handful of survivors. The cornerstone of taredhel lore is the tale of their lost origins in the world they call simply ‘Home’, a place lost in the mists of time. Now they are convinced that Midkemia is that place, and they are coming to reclaim it. Ruthless and arrogant, the taredhel intend to let nothing stand in their way; but before long, Pug and the Conclave realise that it's not necessarily the elves, but the demon horde pursuing them where the true danger lies. And hanging over Pug always is the prophecy that he will be doomed to watch everyone he loves die before him. From HarperCollins UK 13 August 2008 ) Earlier Information Laromendis is a conjurer from another world - a world inhabited by a race of high elves whose home is being ravaged by the Dread Legion of the Demon King. The elves' only hope lies in finding the lost homeworld - Midkemia - and now they must reclaim it, at any cost! Pug summons the help of a warlock and a holy demon-taming cleric, but in doing so, he has unwittingly reunited two former lovers whose parting was bitter ... and who just might have secret agendas of their own"
        },
        {
            title: 'At the Gates of Darkness',
            description: "Recent events have shocked and devastated the Conclave of Shadows; the discovery of the Demon horde that is following the elven invaders of Midkemia; the rise of the mad magician Belasco, and the personal cost paid by Pug and his family. But grieving for lost loved-ones must wait. The followers of the Demon prince have almost succeeded in bringing him through the dimensions. The Conclave must regroup and find a way to meet the approaching evil, whilst trying to stop civil war from destroying Triagia before the demon horde even arrives."
        },
        {
            title: 'A Kingdom Besieged',
            description: " Discover the fate of the original black Magician, Pug, and his motley crew of agents who safeguard the world of Trigia, as prophecy becomes truth in the first book of the last ever Midkemian trilogy. THE KINGDOM BESIEGED The Darkness is coming… The Kingdom is plagued by rumour and instability. Kingdom spies in Kesh have been disappearing - either murdered, or turned to the enemy side. Information has become scant and unreliable; but one thing appears clear. Dark forces are on the move… Since Pug and the Conclave of Shadows enforced peace after the last Keshian invasion, the Empire has offered no threat. But now factions are rising and Jim Dasher reports mobilizations of large forces in the Keshian Confederacy. As the men of the West answer the King's call to muster, Martin conDoin - left as caretaker of Crydee Keep - will suddenly be confronted with the vanguard of an invading army. He reminds himself that he is a year older than his legendary ancestor, Prince Arutha, was when he stood firm against the Tsurani invasion, but Arutha had an army to command, and Martin is left with old men and young boys. Massive events are about to unfold, events which threaten the future of all human life in Midkemia..."
        },
        {
            title: 'A Crown Imperiled',
            description: "The penultimate volume of the mighty Riftwar Cycle War rages in Midkemia but behind the chaos there is disquieting evidence of dark forces at work. Jim Dasher's usually infallible intelligence network has been cleverly dismantled; nowhere is safe. He feels that the world is coming apart at the seams and is helpless to protect his nation. Quiet palace coups are underway in Roldem and Rillanon; and King Gregory of the Isles has yet to produce an heir. In each kingdom a single petty noble has risen from obscurity to threaten the throne. Lord Hal of Crydee and his great friend Ty Hawkins, champion swordsman of the Masters' Court, are entrusted with the task of smuggling Princess Stephané and her lady-in-waiting, the lovely but mysterious Lady Gabriella, out of Roldem to a place of greater safety. But is there any safe haven to be found? Meanwhile, Hal's younger brothers Martin and Brendan are attempting to hold the strategic city of Ylith against an onslaught of Keshian Dog Soldiers, and a mysterious force from beneath the sea. The Kingdom might lose Crydee and recover; but if Ylith falls, all is lost. An unknown player appears to be orchestrating these conflicts. Can Pug and the Conclave of Shadows track down this source before Midkemia is destroyed?"
        },
        {
            title: 'Jimmy and the Crawler',
            description: "The Crawler: a name whispered in fear ... In the crime-ridden back alleys of Krondor a rival gang has sprung up to threaten the Upright Man’s Mockers. Does the Crawler control the rival gang? Where does his power come from? And does it threaten the peace of the Kingdom? James, personal squire to Prince Arutha of Krondor, but in the underworld known as the thief and trickster Jimmy the Hand, must travel to Kesh in disguise. There, working with William, lieutenant of the prince’s household guard and son of the magician Pug, and Jazhara, niece to the Keshian lord Hazara-Khan, he must attempt to unmask the mysterious Crawler and rid Krondor of his influence."
        },
        {
            title: 'Magicans End',
            description: "This book has yet to be released. It will be the final book in The Riftwar Cycle."
        }
    ]
}
